---
title: \textbf{COVID-19 Modeling}
author: "The Policy Lab"
date: \today
output:
    pdf_document:
        keep_tex: true
    beamer_presentation:
        keep_tex: true
        theme: metropolis
geometry: margin=0.5in
---

```{r setup-r, include=FALSE}
library(reticulate)
use_python("/usr/bin/python3")
```

# Introduction

The plots and outputs below ... <BLAH, BLAH, BLAH, MORE, WORDS, HERE>


```{python setup-python, echo = FALSE}

import re
import os
import glob

import warnings

warnings.simplefilter("ignore")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import oyaml as yaml
```

# Hospitalization

```{python get-data, echo = FALSE, results = 'hide'}
with open("config.yml") as f:
    config = yaml.safe_load(f)

dirnames = config["interventions"]["scenarios"]
scenario_names = [dir.replace("_"," ") for dir in dirnames]
death_rate_name = 'med'

r = re.compile('.*minimal_(.*)/.*')
dfs = []
for entry in glob.glob(f'hospitalization/model_output/minimal_*/{death_rate_name}*csv'):
    match = r.match(entry)
    if match:
        dirname = match.groups()[0]
        scenario_name = scenario_names[dirnames.index(dirname)]
        df = pd.read_csv(entry)
        df = df[df['geoid'] // 1000 == 44]  # Pull out RI from the simulation
        df = df[df['comp'] == 'diffI']
        df['scenario_name'] = scenario_name
        dfs.append(df)

df = pd.concat(dfs)

# There are 5 counties in RI
assert (df.groupby(['scenario_name', 'time', 'sim_num']).size() == 5).all()

# Add all counties in RI
grouped = df.groupby(['sim_num', 'time', 'scenario_name'])[['hosp_curr', 'icu_curr', 'incidD', 'incidH', 'incidI']].sum().reset_index()
grouped['time'] = pd.to_datetime(grouped.time)
```

## Hospital Beds Occupied per Day

```{python hosp-beds, echo = FALSE, results = 'hide'}
fig, ax = plt.subplots(figsize=(10, 8))

grouped['Scenario'] = grouped.scenario_name
blah = sns.lineplot(
    data = grouped,
    x = 'time',
    y = 'hosp_curr',
    hue='Scenario',
    ax = ax
)

plt.xticks(rotation=45)
plt.ylabel('Number Hospital Beds Occupied per Day')

box = ax.get_position()
ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])

# Put a legend to the right of the current axis
ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.grid(axis='both')
plt.title('Median bolded; 95% CI in bands')
```

## ICU Beds Occupied per Day


```{python hosp-icu, echo = FALSE, results = 'hide'}
fig, ax = plt.subplots(figsize=(10, 8))

grouped['Scenario'] = grouped.scenario_name
blah = sns.lineplot(
    data = grouped,
    x = 'time',
    y = 'icu_curr',
    hue='Scenario',
    ax = ax
)

plt.xticks(rotation=45)
plt.ylabel('Number ICU Beds Occupied per Day')

box = ax.get_position()
ax.set_position([box.x0, box.y0, box.width * 0.8, box.height])

# Put a legend to the right of the current axis
ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.grid(axis='both')
plt.title('Median bolded; 95% CI in bands')
```

## Hospitalization Statistics


```{python setup-hosp-table, echo = FALSE}
def low_quantile(x):
    return np.quantile(x, 0.025)

def high_quantile(x):
    return np.quantile(x, 0.975)

def create_pivot_display(focus, col):
    pivoted = focus.groupby(['scenario_name', 'months', 'sim_num'])[col].sum().reset_index()\
        .pivot_table(index='scenario_name', columns='months', values=col, aggfunc=[
        'median', low_quantile, high_quantile]).astype(int)
    return (pivoted['median'].applymap(lambda x: '{:,}'.format(x)) +
            '  (' + pivoted['low_quantile'].applymap(lambda x: '{:,}'.format(x)) +
            ' – ' + pivoted['high_quantile'].applymap(lambda x: '{:,}'.format(x)) +
            ')')

```


```{python, echo = FALSE}
focus = grouped[grouped['time'] >= '03-01-2020'].copy()
focus['period'] = focus['time'].dt.month // 2
focus['months'] = focus.period.map({1: '03-04', 2: '05-06', 3: '07-08', 4: '09-10'})

#print('Peak hospital occupancy in period (median + 95% CI)')
pivot = create_pivot_display(focus, 'hosp_curr')
```


```{r hosp-table, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(kableExtra)
library(readr)
library(dplyr)

dat <- py$pivot
kable(dat, align = c("l", rep("r", 4)), booktabs = TRUE) %>%
    kable_styling(full_width = FALSE, font_size = 8)
```
